openapi: 3.0.0
info:
  title: User Management API
  version: 1.0.0
servers:
- url: http://localhost:3000
paths:
  /users:
    get:
      operationId: usersGET
      responses:
        "200":
          description: A list of users
      summary: Get a list of users
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    User:
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
      type: object
